CREATE TABLE LOGST (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MENSAJE VARCHAR(100),
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



DELIMITER //

CREATE PROCEDURE auditoria_Juan()
BEGIN
    INSERT INTO LOGST (MENSAJE)
    VALUES ('Ejecutado desde Juan');
END //



DELIMITER ;

DELIMITER //

CREATE EVENT EventoAuditoria_Juan
ON SCHEDULE EVERY 1 MINUTE
DO
BEGIN
   
    INSERT INTO LOGST (MENSAJE)
    VALUES ('Ejecutado desde Evento');
    CALL auditoria_Juan();
END //

DELIMITER ;